//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuServiceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuArgs", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
        "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.GetMenuHtmlFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.TemplateMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.Menu[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.Menu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.GetMenuPropertiesFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.Claim[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MenuServiceClient.Claim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    public partial class MenuArgs : object
    {
        
        private string EnterpriseUserIdField;
        
        private MenuServiceClient.Claim[] SerializableClaimsCoreField;
        
        private System.Security.Claims.ClaimsIdentity UserClaimsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseUserId
        {
            get
            {
                return this.EnterpriseUserIdField;
            }
            set
            {
                this.EnterpriseUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MenuServiceClient.Claim[] SerializableClaimsCore
        {
            get
            {
                return this.SerializableClaimsCoreField;
            }
            set
            {
                this.SerializableClaimsCoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Security.Claims.ClaimsIdentity UserClaims
        {
            get
            {
                return this.UserClaimsField;
            }
            set
            {
                this.UserClaimsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMenuHtmlFault", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
        "")]
    public partial class GetMenuHtmlFault : object
    {
        
        private int ErrorNumberField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumber
        {
            get
            {
                return this.ErrorNumberField;
            }
            set
            {
                this.ErrorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateMapping", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
        "")]
    public partial class TemplateMapping : object
    {
        
        private string AmfomOnlineHelpUrlField;
        
        private string AmfomPathField;
        
        private string AmfomSumUrlField;
        
        private string BannerColorField;
        
        private string CNONameField;
        
        private string CNOPathField;
        
        private string ClassificationField;
        
        private string CopNameField;
        
        private string CopPathField;
        
        private string EnvironmentDesignationField;
        
        private string HomePortPathField;
        
        private bool IsEnterpriseAdminField;
        
        private string IsafPathField;
        
        private MenuServiceClient.Menu[] MenuField;
        
        private string NextGenPathField;
        
        private string NmetlPathField;
        
        private string NrreBiUrlField;
        
        private string NrreHomeUrlField;
        
        private string OfomOnlineHelpUrlField;
        
        private string OfomPathField;
        
        private string OfomSumUrlField;
        
        private string PfomPathField;
        
        private string SfomOnlineHelpUrlField;
        
        private string SfomPathField;
        
        private string SfomSumUrlField;
        
        private string SpfIIPathField;
        
        private string TimeOutTextField;
        
        private string UserFirstNameField;
        
        private string UserLastNameField;
        
        private string UserRankField;
        
        private string UtilitiesPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmfomOnlineHelpUrl
        {
            get
            {
                return this.AmfomOnlineHelpUrlField;
            }
            set
            {
                this.AmfomOnlineHelpUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmfomPath
        {
            get
            {
                return this.AmfomPathField;
            }
            set
            {
                this.AmfomPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmfomSumUrl
        {
            get
            {
                return this.AmfomSumUrlField;
            }
            set
            {
                this.AmfomSumUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannerColor
        {
            get
            {
                return this.BannerColorField;
            }
            set
            {
                this.BannerColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNOName
        {
            get
            {
                return this.CNONameField;
            }
            set
            {
                this.CNONameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNOPath
        {
            get
            {
                return this.CNOPathField;
            }
            set
            {
                this.CNOPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopName
        {
            get
            {
                return this.CopNameField;
            }
            set
            {
                this.CopNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopPath
        {
            get
            {
                return this.CopPathField;
            }
            set
            {
                this.CopPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnvironmentDesignation
        {
            get
            {
                return this.EnvironmentDesignationField;
            }
            set
            {
                this.EnvironmentDesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePortPath
        {
            get
            {
                return this.HomePortPathField;
            }
            set
            {
                this.HomePortPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnterpriseAdmin
        {
            get
            {
                return this.IsEnterpriseAdminField;
            }
            set
            {
                this.IsEnterpriseAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsafPath
        {
            get
            {
                return this.IsafPathField;
            }
            set
            {
                this.IsafPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MenuServiceClient.Menu[] Menu
        {
            get
            {
                return this.MenuField;
            }
            set
            {
                this.MenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextGenPath
        {
            get
            {
                return this.NextGenPathField;
            }
            set
            {
                this.NextGenPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmetlPath
        {
            get
            {
                return this.NmetlPathField;
            }
            set
            {
                this.NmetlPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrreBiUrl
        {
            get
            {
                return this.NrreBiUrlField;
            }
            set
            {
                this.NrreBiUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrreHomeUrl
        {
            get
            {
                return this.NrreHomeUrlField;
            }
            set
            {
                this.NrreHomeUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfomOnlineHelpUrl
        {
            get
            {
                return this.OfomOnlineHelpUrlField;
            }
            set
            {
                this.OfomOnlineHelpUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfomPath
        {
            get
            {
                return this.OfomPathField;
            }
            set
            {
                this.OfomPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfomSumUrl
        {
            get
            {
                return this.OfomSumUrlField;
            }
            set
            {
                this.OfomSumUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PfomPath
        {
            get
            {
                return this.PfomPathField;
            }
            set
            {
                this.PfomPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SfomOnlineHelpUrl
        {
            get
            {
                return this.SfomOnlineHelpUrlField;
            }
            set
            {
                this.SfomOnlineHelpUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SfomPath
        {
            get
            {
                return this.SfomPathField;
            }
            set
            {
                this.SfomPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SfomSumUrl
        {
            get
            {
                return this.SfomSumUrlField;
            }
            set
            {
                this.SfomSumUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpfIIPath
        {
            get
            {
                return this.SpfIIPathField;
            }
            set
            {
                this.SpfIIPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOutText
        {
            get
            {
                return this.TimeOutTextField;
            }
            set
            {
                this.TimeOutTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFirstName
        {
            get
            {
                return this.UserFirstNameField;
            }
            set
            {
                this.UserFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLastName
        {
            get
            {
                return this.UserLastNameField;
            }
            set
            {
                this.UserLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRank
        {
            get
            {
                return this.UserRankField;
            }
            set
            {
                this.UserRankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilitiesPath
        {
            get
            {
                return this.UtilitiesPathField;
            }
            set
            {
                this.UtilitiesPathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
        "")]
    public partial class Menu : object
    {
        
        private bool ActiveField;
        
        private System.Guid IdField;
        
        private int LinkOrderField;
        
        private int MenuLevelField;
        
        private string NameField;
        
        private MenuServiceClient.Menu[] SubMenuField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinkOrder
        {
            get
            {
                return this.LinkOrderField;
            }
            set
            {
                this.LinkOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuLevel
        {
            get
            {
                return this.MenuLevelField;
            }
            set
            {
                this.MenuLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MenuServiceClient.Menu[] SubMenu
        {
            get
            {
                return this.SubMenuField;
            }
            set
            {
                this.SubMenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMenuPropertiesFault", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
        "")]
    public partial class GetMenuPropertiesFault : object
    {
        
        private int ErrorNumberField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumber
        {
            get
            {
                return this.ErrorNumberField;
            }
            set
            {
                this.ErrorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Claim", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Claims")]
    public partial class Claim : object
    {
        
        private string m_issuerField;
        
        private string m_originalIssuerField;
        
        private System.Collections.Generic.Dictionary<string, string> m_propertiesField;
        
        private string m_typeField;
        
        private string m_valueField;
        
        private string m_valueTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_issuer
        {
            get
            {
                return this.m_issuerField;
            }
            set
            {
                this.m_issuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_originalIssuer
        {
            get
            {
                return this.m_originalIssuerField;
            }
            set
            {
                this.m_originalIssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> m_properties
        {
            get
            {
                return this.m_propertiesField;
            }
            set
            {
                this.m_propertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_type
        {
            get
            {
                return this.m_typeField;
            }
            set
            {
                this.m_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_value
        {
            get
            {
                return this.m_valueField;
            }
            set
            {
                this.m_valueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_valueType
        {
            get
            {
                return this.m_valueTypeField;
            }
            set
            {
                this.m_valueTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuServiceClient.IMenuService")]
    public interface IMenuService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuHtml", ReplyAction="http://tempuri.org/IMenuService/GetMenuHtmlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MenuServiceClient.GetMenuHtmlFault), Action="http://tempuri.org/IMenuService/GetMenuHtmlGetMenuHtmlFaultFault", Name="GetMenuHtmlFault", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
            "")]
        System.Threading.Tasks.Task<string> GetMenuHtmlAsync(MenuServiceClient.MenuArgs menuArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAdminHtml", ReplyAction="http://tempuri.org/IMenuService/GetAdminHtmlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MenuServiceClient.GetMenuHtmlFault), Action="http://tempuri.org/IMenuService/GetAdminHtmlGetMenuHtmlFaultFault", Name="GetMenuHtmlFault", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
            "")]
        System.Threading.Tasks.Task<string> GetAdminHtmlAsync(MenuServiceClient.MenuArgs menuArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuProperties", ReplyAction="http://tempuri.org/IMenuService/GetMenuPropertiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MenuServiceClient.GetMenuPropertiesFault), Action="http://tempuri.org/IMenuService/GetMenuPropertiesGetMenuPropertiesFaultFault", Name="GetMenuPropertiesFault", Namespace="http://schemas.datacontract.org/2004/07/NavyReadiness.MenuService.Business.Models" +
            "")]
        System.Threading.Tasks.Task<MenuServiceClient.TemplateMapping> GetMenuPropertiesAsync(MenuServiceClient.MenuArgs menuArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IMenuServiceChannel : MenuServiceClient.IMenuService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class MenuServiceClient : System.ServiceModel.ClientBase<MenuServiceClient.IMenuService>, MenuServiceClient.IMenuService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MenuServiceClient() : 
                base(MenuServiceClient.GetDefaultBinding(), MenuServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.nettcp.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MenuServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MenuServiceClient.GetBindingForEndpoint(endpointConfiguration), MenuServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MenuServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MenuServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MenuServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MenuServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetMenuHtmlAsync(MenuServiceClient.MenuArgs menuArgs)
        {
            return base.Channel.GetMenuHtmlAsync(menuArgs);
        }
        
        public System.Threading.Tasks.Task<string> GetAdminHtmlAsync(MenuServiceClient.MenuArgs menuArgs)
        {
            return base.Channel.GetAdminHtmlAsync(menuArgs);
        }
        
        public System.Threading.Tasks.Task<MenuServiceClient.TemplateMapping> GetMenuPropertiesAsync(MenuServiceClient.MenuArgs menuArgs)
        {
            return base.Channel.GetMenuPropertiesAsync(menuArgs);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nettcp))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nettcp))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost/MenuService/MenuService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MenuServiceClient.GetBindingForEndpoint(EndpointConfiguration.nettcp);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MenuServiceClient.GetEndpointAddress(EndpointConfiguration.nettcp);
        }
        
        public enum EndpointConfiguration
        {
            
            nettcp,
        }
    }
}
